# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f2b03df1cd6357da1a35e9c3482ed7dc1d5b4e5a31c182e4943b675b45d772ad7d6fd0a9aec0cd7f5f363dfc1a2bbf4e9939f48886f129e6c8a0fdf2f78cbe1

test:
  secret_key_base: 76ae64752de23c871c82a1a9aba537c0c3dd5de1785acb47bba207b5527ab26a5a8b37d5bb8121c30153caf366add63163144544928560972dc5f0ba7fcb30dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
